{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ddd191f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# SHARED MODULE for the KD teacher-student track (S1..S6a)\n",
    "# Import this from each stage's ensemble script -- avoids\n",
    "# retyping the same encoder classes 5 times with the risk of a\n",
    "# transcription mistake breaking checkpoint loading.\n",
    "# ============================================================\n",
    "import os\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "\n",
    "LABEL_NAMES = [\"Wake\", \"N1\", \"N2\", \"N3\", \"REM\"]\n",
    "\n",
    "\n",
    "def load_3way_split(split_path):\n",
    "    train_p = os.path.join(split_path, \"_train_subs.npy\")\n",
    "    val_p   = os.path.join(split_path, \"_val_subs.npy\")\n",
    "    test_p  = os.path.join(split_path, \"_test_subs.npy\")\n",
    "    for p, name in [(train_p, \"_train_subs.npy\"), (val_p, \"_val_subs.npy\"), (test_p, \"_test_subs.npy\")]:\n",
    "        if not os.path.exists(p):\n",
    "            raise FileNotFoundError(f\"{name} not found at {split_path}\")\n",
    "    train_subs = np.load(train_p, allow_pickle=True).tolist()\n",
    "    val_subs   = np.load(val_p, allow_pickle=True).tolist()\n",
    "    test_subs  = np.load(test_p, allow_pickle=True).tolist()\n",
    "    assert set(train_subs).isdisjoint(val_subs)\n",
    "    assert set(train_subs).isdisjoint(test_subs)\n",
    "    assert set(val_subs).isdisjoint(test_subs)\n",
    "    return train_subs, val_subs, test_subs\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# STUDENT PER-EPOCH ENCODERS -- identical across S1, S2, S4, S5, S6a\n",
    "# (copied verbatim from your S1/S4/S5 scripts; do not edit\n",
    "# independently in each ensemble script or checkpoints will\n",
    "# fail to load with a shape/key mismatch)\n",
    "# ============================================================\n",
    "class ZmaxEEGEncoder(nn.Module):\n",
    "    \"\"\"Compact multi-scale CNN + BiGRU for raw Zmax EEG (2ch, 1920 samples @ 64Hz).\"\"\"\n",
    "    def __init__(self, in_ch=2, d_model=96, dropout=0.3):\n",
    "        super().__init__()\n",
    "        mid = d_model // 2\n",
    "\n",
    "        def branch(kernel):\n",
    "            return nn.Sequential(\n",
    "                nn.Conv1d(in_ch, mid, kernel_size=kernel, stride=4, padding=kernel // 2),\n",
    "                nn.BatchNorm1d(mid), nn.GELU(),\n",
    "                nn.MaxPool1d(2, 2), nn.Dropout(dropout),\n",
    "            )\n",
    "\n",
    "        self.small, self.large = branch(15), branch(60)\n",
    "        with torch.no_grad():\n",
    "            dummy = torch.zeros(1, in_ch, 1920)\n",
    "            L_s, L_l = self.small(dummy).shape[2], self.large(dummy).shape[2]\n",
    "        target_L = min(L_s, L_l)\n",
    "        self.pool_s = nn.AdaptiveAvgPool1d(target_L)\n",
    "        self.pool_l = nn.AdaptiveAvgPool1d(target_L)\n",
    "        self.proj = nn.Sequential(nn.Conv1d(2 * mid, d_model, kernel_size=1),\n",
    "                                   nn.BatchNorm1d(d_model), nn.GELU())\n",
    "        self.gru = nn.GRU(d_model, d_model // 2, batch_first=True, bidirectional=True)\n",
    "        self.norm = nn.LayerNorm(d_model)\n",
    "\n",
    "    def forward(self, x):\n",
    "        # x: (N, 2, 1920) where N = B or B*W depending on caller\n",
    "        fs, fl = self.pool_s(self.small(x)), self.pool_l(self.large(x))\n",
    "        feat = self.proj(torch.cat([fs, fl], dim=1)).permute(0, 2, 1)\n",
    "        gru_out, _ = self.gru(feat)\n",
    "        return self.norm(feat.mean(dim=1) + gru_out.mean(dim=1))\n",
    "\n",
    "\n",
    "class E4Encoder(nn.Module):\n",
    "    \"\"\"1D-CNN + BiGRU for E4 (3ch: BVP, HR, TEMP, 1920 samples @ 64Hz).\"\"\"\n",
    "    def __init__(self, in_ch=3, d_model=96, dropout=0.3):\n",
    "        super().__init__()\n",
    "        self.conv = nn.Sequential(\n",
    "            nn.Conv1d(in_ch, d_model // 2, kernel_size=15, stride=4, padding=7),\n",
    "            nn.BatchNorm1d(d_model // 2), nn.GELU(),\n",
    "            nn.MaxPool1d(2, 2),\n",
    "            nn.Conv1d(d_model // 2, d_model, kernel_size=8, padding=4),\n",
    "            nn.BatchNorm1d(d_model), nn.GELU(),\n",
    "            nn.MaxPool1d(2, 2), nn.Dropout(dropout),\n",
    "        )\n",
    "        self.gru = nn.GRU(d_model, d_model // 2, batch_first=True, bidirectional=True)\n",
    "        self.norm = nn.LayerNorm(d_model)\n",
    "\n",
    "    def forward(self, x):\n",
    "        feat = self.conv(x).permute(0, 2, 1)\n",
    "        gru_out, _ = self.gru(feat)\n",
    "        return self.norm(feat.mean(dim=1) + gru_out.mean(dim=1))\n",
    "\n",
    "\n",
    "class InterEpochAggregator(nn.Module):\n",
    "    \"\"\"Used by S5/S6a only. Aggregates a (B, W, d_model) window of\n",
    "    per-epoch embeddings via BiGRU, returns the CENTER epoch's\n",
    "    contextualized representation.\"\"\"\n",
    "    def __init__(self, d_model=96, context=7):\n",
    "        super().__init__()\n",
    "        self.context = context\n",
    "        self.gru = nn.GRU(d_model, d_model // 2, batch_first=True, bidirectional=True)\n",
    "        self.norm = nn.LayerNorm(d_model)\n",
    "\n",
    "    def forward(self, x):\n",
    "        gru_out, _ = self.gru(x)\n",
    "        contextualized = self.norm(x + gru_out)\n",
    "        return contextualized[:, self.context, :]\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# S1 / S2 / S4 MODEL: single-epoch concat fusion (identical\n",
    "# architecture across all three -- only the loss/training differs)\n",
    "# ============================================================\n",
    "class WearableBaselineModel(nn.Module):\n",
    "    def __init__(self, d_model=96, n_classes=5, dropout=0.3):\n",
    "        super().__init__()\n",
    "        self.zmax_enc = ZmaxEEGEncoder(in_ch=2, d_model=d_model, dropout=dropout)\n",
    "        self.e4_enc = E4Encoder(in_ch=3, d_model=d_model, dropout=dropout)\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.LayerNorm(d_model * 2), nn.Linear(d_model * 2, 64), nn.GELU(),\n",
    "            nn.Dropout(dropout), nn.Linear(64, n_classes)\n",
    "        )\n",
    "\n",
    "    def forward(self, zmax_x, e4_x):\n",
    "        z = self.zmax_enc(zmax_x)\n",
    "        e = self.e4_enc(e4_x)\n",
    "        fused = torch.cat([z, e], dim=1)\n",
    "        return self.classifier(fused)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# S5 MODEL: context-window student\n",
    "# ============================================================\n",
    "class ContextStudentModel(nn.Module):\n",
    "    def __init__(self, d_model=96, n_classes=5, dropout=0.3, context=7):\n",
    "        super().__init__()\n",
    "        self.context = context\n",
    "        self.zmax_enc = ZmaxEEGEncoder(in_ch=2, d_model=d_model, dropout=dropout)\n",
    "        self.e4_enc = E4Encoder(in_ch=3, d_model=d_model, dropout=dropout)\n",
    "        self.zmax_agg = InterEpochAggregator(d_model=d_model, context=context)\n",
    "        self.e4_agg = InterEpochAggregator(d_model=d_model, context=context)\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.LayerNorm(d_model * 2), nn.Linear(d_model * 2, 64), nn.GELU(),\n",
    "            nn.Dropout(dropout), nn.Linear(64, n_classes)\n",
    "        )\n",
    "\n",
    "    def forward(self, zmax_x, e4_x):\n",
    "        # zmax_x: (B, W, 2, 1920)  e4_x: (B, W, 3, 1920)\n",
    "        B, W, Cz, Tz = zmax_x.shape\n",
    "        _, _, Ce, Te = e4_x.shape\n",
    "        z_flat = self.zmax_enc(zmax_x.reshape(B * W, Cz, Tz)).view(B, W, -1)\n",
    "        e_flat = self.e4_enc(e4_x.reshape(B * W, Ce, Te)).view(B, W, -1)\n",
    "        z_ctx = self.zmax_agg(z_flat)\n",
    "        e_ctx = self.e4_agg(e_flat)\n",
    "        fused = torch.cat([z_ctx, e_ctx], dim=1)\n",
    "        return self.classifier(fused)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# S6a MODEL: modality-aware student (same backbone as S5 + aux\n",
    "# heads that are unused at inference)\n",
    "# ============================================================\n",
    "class ModalityAwareStudentModel(nn.Module):\n",
    "    def __init__(self, d_model=96, n_classes=5, dropout=0.3, context=7):\n",
    "        super().__init__()\n",
    "        self.context = context\n",
    "        self.zmax_enc = ZmaxEEGEncoder(in_ch=2, d_model=d_model, dropout=dropout)\n",
    "        self.e4_enc = E4Encoder(in_ch=3, d_model=d_model, dropout=dropout)\n",
    "        self.zmax_agg = InterEpochAggregator(d_model=d_model, context=context)\n",
    "        self.e4_agg = InterEpochAggregator(d_model=d_model, context=context)\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.LayerNorm(d_model * 2), nn.Linear(d_model * 2, 64), nn.GELU(),\n",
    "            nn.Dropout(dropout), nn.Linear(64, n_classes)\n",
    "        )\n",
    "        self.zmax_aux_classifier = nn.Sequential(\n",
    "            nn.LayerNorm(d_model), nn.Linear(d_model, 32), nn.GELU(),\n",
    "            nn.Dropout(dropout), nn.Linear(32, n_classes)\n",
    "        )\n",
    "        self.e4_aux_classifier = nn.Sequential(\n",
    "            nn.LayerNorm(d_model), nn.Linear(d_model, 32), nn.GELU(),\n",
    "            nn.Dropout(dropout), nn.Linear(32, n_classes)\n",
    "        )\n",
    "\n",
    "    def forward(self, zmax_x, e4_x):\n",
    "        B, W, Cz, Tz = zmax_x.shape\n",
    "        _, _, Ce, Te = e4_x.shape\n",
    "        z_flat = self.zmax_enc(zmax_x.reshape(B * W, Cz, Tz)).view(B, W, -1)\n",
    "        e_flat = self.e4_enc(e4_x.reshape(B * W, Ce, Te)).view(B, W, -1)\n",
    "        z_ctx = self.zmax_agg(z_flat)\n",
    "        e_ctx = self.e4_agg(e_flat)\n",
    "        fused = torch.cat([z_ctx, e_ctx], dim=1)\n",
    "        main_logits = self.classifier(fused)\n",
    "        zmax_aux_logits = self.zmax_aux_classifier(z_ctx)\n",
    "        e4_aux_logits = self.e4_aux_classifier(e_ctx)\n",
    "        return main_logits, zmax_aux_logits, e4_aux_logits\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# SHARED: soft-vote ensemble inference + CSV export with\n",
    "# subject_id already attached (no separate reconstruction step\n",
    "# needed downstream in the significance script)\n",
    "# ============================================================\n",
    "def save_ensemble_predictions_csv(out_csv, subject_ids, true_labels, pred_labels, avg_probs):\n",
    "    import csv as csv_module\n",
    "    with open(out_csv, 'w', newline='') as f:\n",
    "        writer = csv_module.writer(f)\n",
    "        writer.writerow([\"subject_id\", \"true_label\", \"predicted_label\",\n",
    "                          \"true_class\", \"predicted_class\",\n",
    "                          \"prob_Wake\", \"prob_N1\", \"prob_N2\", \"prob_N3\", \"prob_REM\"])\n",
    "        for sid, t, p, probs in zip(subject_ids, true_labels, pred_labels, avg_probs):\n",
    "            writer.writerow([sid, int(t), int(p), LABEL_NAMES[int(t)], LABEL_NAMES[int(p)],\n",
    "                              *[f\"{x:.6f}\" for x in probs]])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8a52e0f2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
